---
- name: update web & nfs servers
  hosts: webserver, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark
      yum:
        name: wireshark
        state: removed

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark
      apt: 
        name: wireshark-qt
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes
        
- name: update db server
  hosts: db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: delete wireshark
      yum: 
        name: wireshark-qt
        state: absent
        autoremove: yes
        purge: yes
        autoclean: yes
