---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
- name: Include dynamic variables 
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: uat-webserver
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webserver.yml
