---
- hosts: all
- name: Include dynamic variables 
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: uat-webserver
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webserver.yml
