---
- hosts: all
- name: Include dynamic variables 
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always
    
- hosts: sonar
- name: Sonarqube installation
  import_playbook: ../static-assignments/sonar.yml
